### ISSUE TITLE
Syntax error while trying to get slave info

### ISSUE THREAD

**Issue by vladcenan** [myntra/Analyse-Redis-Cluster-nodes#1]
It returns syntax error when trying to get slave info:
for (var in hash) {IFS=":" read -ra master <<< freq[var, "master"] ;master_ip = master[0]}}
......................................................................................^ syntax error

**Comment by sidd081-zz** [comment]
@vladcenan I have updated the script, please use new one and revert

**Comment by vladcenan** [comment]
The update solved the issue.Thanks!
